<?php

/**
 * @file
 * Provides a cep_parser entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function cep_parser_theme() {
  return [
    'cep_parser' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for cep_parser templates.
 *
 * Default template: cep-parser.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the cep_parser information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_cep_parser(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
